# Imports

In [1]:
# imports
import pennylane as qml
import numpy as np
import torch
from torch.autograd import Variable
from sklearn.preprocessing import MinMaxScaler
from torch.utils.tensorboard import SummaryWriter

In [2]:
import torch
import pennylane as qml
from qml_mor.models import IQPEReuploadSU2Parity, ModelType
from torch.utils.data import TensorDataset, DataLoader

num_samples=1
num_qubits = 3
num_reups = 1
num_layers = 1
sizex = num_qubits

omega = 0.0
init_theta = torch.randn(num_reups, num_qubits, requires_grad=True)
theta = torch.randn(
    num_reups, num_layers, num_qubits - 1, 2, requires_grad=True
)
W = torch.randn(2**num_qubits, requires_grad=True)

params = [init_theta, theta, W]

dev = qml.device("default.qubit", wires=num_qubits, shots=None)

model = IQPEReuploadSU2Parity(dev, params)
X = torch.randn(10, 3)
Ypred = model(X)
print(Ypred)

tensor([-0.0641,  0.8303,  1.9528,  1.3994,  1.1039, -0.2923, -0.3612,  1.4603,
         0.2584,  0.2070], dtype=torch.float64, grad_fn=<StackBackward0>)


In [3]:
from torch.nn import Parameter
P = model.parameters()
for p in P:
    print(p)
print("====================")
save = model.state_dict().copy()

init_theta = torch.randn(num_reups, num_qubits, requires_grad=True)
theta = torch.randn(
    num_reups, num_layers, num_qubits - 1, 2, requires_grad=True
)
W = torch.randn(2**num_qubits, requires_grad=True)

params = [init_theta, theta, W]

model = IQPEReuploadSU2Parity(dev, params)

P = model.parameters()
for p in P:
    print(p)
print("====================")
model.load_state_dict(save)
P = model.parameters()
for p in P:
    print(p)
print("====================")
print(save)

Parameter containing:
tensor([[1.1926, 1.5488, 0.0846]], requires_grad=True)
Parameter containing:
tensor([[[[ 0.1741, -0.0099],
          [ 0.6962,  0.2820]]]], requires_grad=True)
Parameter containing:
tensor([-2.2230,  0.2563,  0.1263,  0.3330,  0.0443, -1.6297,  1.3642,  0.7304],
       requires_grad=True)
Parameter containing:
tensor([[-0.1384, -0.5148,  0.8741]], requires_grad=True)
Parameter containing:
tensor([[[[-1.2465, -0.8230],
          [ 1.1152, -0.1576]]]], requires_grad=True)
Parameter containing:
tensor([-2.5465, -0.1992, -1.9099,  0.7021, -0.2655, -0.1603, -0.3290, -0.2656],
       requires_grad=True)
Parameter containing:
tensor([[1.1926, 1.5488, 0.0846]], requires_grad=True)
Parameter containing:
tensor([[[[ 0.1741, -0.0099],
          [ 0.6962,  0.2820]]]], requires_grad=True)
Parameter containing:
tensor([-2.2230,  0.2563,  0.1263,  0.3330,  0.0443, -1.6297,  1.3642,  0.7304],
       requires_grad=True)
OrderedDict([('init_theta', tensor([[1.1926, 1.5488, 0.0846]]

In [4]:
N = 10
torch.manual_seed(0)
X = torch.randn(N, num_qubits, dtype=torch.float64)
Y = torch.randn(N, dtype=torch.float64) 
batch_size=2
shuffle=False

dataset = TensorDataset(X, Y)
loader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

In [7]:
from qml_mor.trainer import RegressionTraining
from torch.utils.tensorboard import SummaryWriter
from torch.optim import Adam
from datetime import datetime

optimizer = Adam(model.parameters(), lr=0.1, amsgrad=True)
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
writer = SummaryWriter('runs/trainer_{}'.format(timestamp))
loss_fn = torch.nn.MSELoss()
training = RegressionTraining(optimizer, loss_fn, writer)
loss = training.train(model, loader, loader)
print(loss)
writer.close()

4.001237484375805e-05


In [8]:
Ypred = model(X)
print(Y)
print("==============")
print(Ypred)

tensor([ 0.1894, -0.2190,  2.0576, -0.0354,  0.0627, -0.7663,  1.0993,  2.7565,
         0.1753, -0.9315], dtype=torch.float64)
tensor([ 0.1965, -0.2223,  2.0510, -0.0397,  0.0507, -0.7760,  1.0901,  2.7514,
         0.1716, -0.9424], dtype=torch.float64, grad_fn=<StackBackward0>)


In [ ]:
%load_ext tensorboard
%tensorboard --logdir runs/fashion_trainer_20230517_113403

In [ ]:
import torch
import pennylane as qml
from torch.utils.data import TensorDataset, DataLoader
from qml_mor.models import IQPEReuploadSU2Parity
from qml_mor.trainer import AdamTorch
from qml_mor.datagen import DataGenCapacity

num_samples=1
num_qubits = 3
num_reups = 1
num_layers = 1
sizex = num_qubits

datagen = DataGenCapacity(sizex=sizex, num_samples=num_samples)

omega = 0.0
init_theta = torch.randn(num_reups, num_qubits, requires_grad=True)
theta = torch.randn(
    num_reups, num_layers, num_qubits - 1, 2, requires_grad=True
)
W = torch.randn(2**num_qubits, requires_grad=True)

params = [init_theta, theta, W]

model = IQPEReuploadSU2Parity(omega)
dev = qml.device("default.qubit", wires=num_qubits, shots=None)

@qml.qnode(dev, interface="torch")
def qnn_model(x, params):
    return model.qfunction(x, params)

loss_fn = torch.nn.MSELoss()
num_epochs = 300
opt = AdamTorch(params, loss_fn, num_epochs=num_epochs, amsgrad=True)

N = 10
batch_size=int("inf")
shuffle=True
data = datagen.gen_data(N)
X = data["X"]
Y = data["Y"][0]
dataset = TensorDataset(X, Y)
loader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

opt_params = opt.optimize(qnn_model, loader)

In [ ]:
Nx = X.size(0)
y_pred = torch.stack([qnn_model(X[k], opt_params) for k in range(Nx)])
mre = torch.mean(torch.abs((Y - y_pred) / y_pred))

print(mre)
print(loss_fn(y_pred, Y))

In [ ]:
import torch
from torch.utils.data import TensorDataset, DataLoader
X = torch.randn(5, 3)
Y = torch.randn(5)
batch_size = 2

dataset = TensorDataset(X, Y)
shuffle = True
loader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

print(X)
print(Y)
print("===========")
for X_, Y_ in loader:
    print(X_.size(0))
    print(X_)
    print(Y_)
    print("***********")

In [ ]:
from qml_mor.datagen import DataGenRademacher, NormalPrior
prior = NormalPrior(3, seed=0)
radem = DataGenRademacher(prior, 2, 3, seed=None)
data = radem.gen_data(4)
print(data)

In [ ]:
num = 5
bistring = bin(num)[2:]
print(type(bistring))
print(bistring)

In [ ]:
import pennylane as qml
import torch
from qml_mor.models import IQPEReuploadSU2Parity

num_qubits  = 3
num_reps    = 2
num_layers  = 2
omega       = 1.
torch.manual_seed(0)
x           = torch.randn(num_qubits, requires_grad=False)
init_theta  = torch.randn(num_reps, num_qubits, requires_grad=True)
theta       = torch.randn(num_reps, num_layers, num_qubits-1, 2, requires_grad=True)
W           = torch.randn(2**num_qubits, requires_grad=True)

params = [init_theta, theta, W]

def iqpe_reupload_su2_parity(
    x, init_theta, theta, W, omega: float = 0.0
):
    """
    Quantum function that calculates the expectation value
    of the parity of Pauli Z operators.

    Args:
        x (Tensor): Input tensor of shape (num_qubits,)
        init_theta (Tensor): Initial rotation angles for each qubit,
            of shape (reps, num_qubits)
        theta (Tensor): Rotation angles for each layer and each qubit,
            of shape (reps, num_layers, num_qubits-1, 2)
        W (Tensor): Observable weights of shape (2^num_qubits,)
        omega (float, optional): Exponential feature scaling factor. Defaults to 0.0.

    Returns:
        QFuncOutput: Expectation value of the parity of Pauli Z operators
    """

    shape_init = init_theta.shape
    shape = theta.shape
    if len(shape_init) != 2:
        raise ValueError("Initial theta must be a 2-dim tensor")
    if len(shape) != 4:
        raise ValueError("Theta must be a 4-dim tensor")

    num_qubits = len(x)
    reps = shape_init[0]
    wires = range(num_qubits)

    for layer in range(reps):
        features = 2 ** (omega * layer) * x
        initial_layer_weights = init_theta[layer]
        weights = theta[layer]

        qml.IQPEmbedding(features=features, wires=wires)
        qml.SimplifiedTwoDesign(
            initial_layer_weights=initial_layer_weights,
            weights=weights,
            wires=wires,
        )

def iqpe_reupload_su2_meas(
    x, init_theta, theta, W, omega: float = 0.0
):
    iqpe_reupload_su2_parity(x, init_theta, theta, W, omega)
    obs = parities(len(x))
    H = qml.Hamiltonian(W, obs)

    return qml.sample()

#qnn_model = IQPEReuploadSU2Parity(params, omega=1.0)

dev = qml.device("default.qubit", wires=num_qubits, shots=None)
qnode = qml.QNode(iqpe_reupload_su2_meas, dev, interface="torch")
#drawer = qml.draw(qnode, expansion_strategy="device")
#print(drawer(x, init_theta, theta, W))
probs = qnode(x, init_theta, theta, W, omega)
probs

In [ ]:
samples = probs
bitstrings = [''.join(str(b.item()) for b in sample) for sample in samples]
bitstring_counts = {bs: bitstrings.count(bs) for bs in set(bitstrings)}
print(samples)
print(bitstrings)
print(bitstring_counts)

In [ ]:
from qml_mor.models import IQPEReuploadSU2Parity

model = IQPEReuploadSU2Parity()

qnode = qml.QNode(model.probabilities, dev, interface="torch")
probs = qnode(x, params)
print(probs)
print(model.Hamiltonian(params))

In [ ]:
H = model.Hamiltonian(params)
sum = 0.0
b = "110"

for idx, O in enumerate(H.ops):

    if not isinstance(O.name, list):
        if O.name == "Identity":
            sum += H.coeffs[idx]
        elif O.name == "PauliZ":
            i = O.wires[0]
            sign = (-1)**(int(b[-1-i]))
            sum += sign*H.coeffs[idx]
        else:
            raise ValueError("All operators must be PauliZ or Identity.")
    else:
        if not all(name=="PauliZ" for name in O.name):
            raise ValueError("All operators must be PauliZ or Identity.")
        
        sign = 1
        for w in O.wires:
            sign *= (-1)**(int(b[-1-w]))

        sum += sign*H.coeffs[idx]

In [ ]:
print(probs)
marginal = qml.math.marginal_prob(probs, axis=[0])
print(marginal)

In [ ]:
from qml_mor.models import parities

n = 3
test = parities(n)
H = qml.Hamiltonian(W, test)
print(H)
print(H.ops)

# Model Definition

In [ ]:
# feature layer
def feature_layer(x):
    num_qubits = len(x)
    qml.IQPEmbedding(x, wires=range(num_qubits))

In [ ]:
# variational layer
def variational_layer(init_theta, theta, num_qubits):
    qml.SimplifiedTwoDesign(initial_layer_weights=init_theta, weights=theta, wires=range(num_qubits))

In [ ]:
# observable / output layer
def sequence_generator(n):
    if n == 0:
        return [[]]
    else:
        sequences = []
        for sequence in sequence_generator(n-1):
            sequences.append(sequence + [n-1])
            sequences.append(sequence)
        return sequences
    
def parities(n):
    
    seq = sequence_generator(n)
    ops = []
    for par in seq:
        if par:
            tmp = qml.PauliZ(par[0])
            if len(par) > 1:
                for i in par[1:]:
                    tmp = tmp @ qml.PauliZ(i)

            ops.append(tmp)

    ops.append(qml.Identity(0))

    return ops

In [ ]:
from pennylane.templates import IQPEmbedding, SimplifiedTwoDesign
# QNN model
@qml.qnode(dev, interface='torch')
def qnn_model(x, init_theta, theta, W, omega=0.):

    num_qubits = len(x)
    shape_init = init_theta.shape
    reps       = 1
    if len(shape_init) < 1:
        init_theta = [init_theta]
        shape_init = init_theta.shape
    reps       = shape_init[0]

    shape_theta = theta.shape
    reps_       = 1
    if len(shape_theta) < 3:
        theta       = [theta]
        shape_theta = theta.shape
    reps_       = shape_theta[0]

    assert reps == reps_
    for l in range(reps):
        qml.IQPEmbedding(features=2**(omega*l)*x, wires=range(num_qubits))
        qml.SimplifiedTwoDesign(initial_layer_weights=init_theta[l], weights=theta[l], wires=range(num_qubits))

    obs = parities(num_qubits)
    H   = qml.Hamiltonian(W, obs)

    return qml.expval(H)

In [ ]:
import pennylane as qml
from pennylane.templates import IQPEmbedding

n_wires = 3
n_layers = 2

dev = qml.device("default.qubit", wires=n_wires)
@qml.qnode(dev, interface='torch')
def iqpe_circuit(features):
    for layer in range(n_layers):
        # Apply the IQPEmbedding template in a loop
        IQPEmbedding(features=features[layer], wires=range(n_wires))

    return [qml.expval(qml.PauliZ(wires=i)) for i in range(n_wires)]

features = np.random.random((n_layers, n_wires))

result1 = iqpe_circuit(features)

In [ ]:
num_qubits  = 3
num_reps    = 0
num_layers  = 0
omega       = 1.
x           = torch.randn(num_qubits, requires_grad=False)
init_theta  = torch.randn(num_reps, num_qubits, requires_grad=True)
theta       = torch.randn(num_reps, num_layers, num_qubits-1, 2, requires_grad=True)
W           = torch.randn(2**num_qubits, requires_grad=True)

result1 = qnn_model(x, init_theta, theta, W)
result2 = qnn_model(x, init_theta, theta, W)

ret = torch.stack([result1, result2])
result1.size()

In [ ]:
from scipy.stats import qmc
def generate_samples_r(d, S):
    sampler = qmc.LatinHypercube(d=d)
    r_samples = sampler.random(n=S)
    return r_samples
r = generate_samples_r(10, 2)
print(len(r[0]))

tmp = set()
rng = np.random.default_rng(seed=0)
b1 = tuple(rng.integers(0, 2, size=4))
b2 = tuple(rng.integers(0, 2, size=4))
tmp.add(b1)
tmp.add(b2)
print(tmp)
arr = np.array(list(tmp))
print(arr)
arr[0, 3]

In [ ]:
import torch

# Original list of tensors
tensor_list = [torch.tensor([1., 2., 3.], requires_grad=True),
               torch.tensor([4., 5., 6.], requires_grad=False)]

est_params = [
                        t.detach().clone().requires_grad_(t.requires_grad)
                        for t in tensor_list
                    ]
tensor_list *= 2
print(tensor_list)
print(est_params)

In [ ]:
msg = (f"Stopping early\n"
       "Loss not improving")
print(msg)

In [ ]:
import pennylane as qml
import torch
import torch.optim as optim
import torch.nn as nn

# Define the quantum device
dev = qml.device("default.qubit", wires=2)

# Define the custom model as a PennyLane QNode
@qml.qnode(dev, interface="torch")
def custom_model(x, y):
    # Apply your quantum circuit here, which uses input x and trainable parameters y
    # As an example, we'll use a simple circuit with one rotation gate parameterized by y:
    qml.RY(y[0], wires=0)
    qml.RX(x, wires=1)
    qml.CNOT(wires=[0, 1])
    return qml.expval(qml.PauliZ(1))

# Define the dataset (x_data, y_data)
x_data = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5], dtype=torch.float32)
y_data = torch.tensor([0.5, 0.4, 0.3, 0.2, 0.1], dtype=torch.float32)

# Initialize the trainable parameters
params = torch.tensor([0.0], dtype=torch.float32, requires_grad=True)

# Set the hyperparameters
learning_rate = 0.01
epochs = 100
loss_fn = nn.MSELoss()
optimizer = optim.Adam([params], lr=learning_rate)

# Training loop
for epoch in range(epochs):
    optimizer.zero_grad()

    # Forward pass
    predictions = torch.tensor([custom_model(x, params) for x in x_data], dtype=torch.float32)
    loss = loss_fn(predictions, y_data)

    # Backward pass
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch + 1}, Loss: {loss.item()}")

print(f"Trained parameters: {params}")

In [ ]:
num_qubits  = 3
num_reps    = 3
num_layers  = 0
omega       = 1.
x           = torch.randn(num_qubits, requires_grad=False)
init_theta  = torch.randn(num_reps, num_qubits, requires_grad=True)
theta       = torch.randn(num_reps, num_layers, num_qubits-1, 2, requires_grad=True)
W           = torch.randn(2**num_qubits, requires_grad=True)
def qnn_model(x, init_theta, theta, W, omega=0.):

    num_qubits = len(x)
    shape_init = init_theta.shape
    reps       = 1
    if len(shape_init) < 1:
        init_theta = [init_theta]
        shape_init = init_theta.shape
    reps       = shape_init[0]

    shape_theta = theta.shape
    reps_       = 1
    if len(shape_theta) < 3:
        theta       = [theta]
        shape_theta = theta.shape
    reps_       = shape_theta[0]

    assert reps == reps_
    for l in range(reps):
        qml.IQPEmbedding(features=2**(omega*l)*x, wires=range(num_qubits))
        qml.SimplifiedTwoDesign(initial_layer_weights=init_theta[l], weights=theta[l], wires=range(num_qubits))

    obs = parities(num_qubits)
    H   = qml.Hamiltonian(W, obs)

    return qml.expval(H)

result = qnn_model(x, init_theta, theta, W)
print(result.shape())

In [ ]:
tmp = parities(3)
for x in tmp:
    print(type(x))
    print(issubclass(type(x), qml.operation.Observable))

In [ ]:
# example
num_qubits  = 3
num_reps    = 3
num_layers  = 0
omega       = 1.
x           = torch.randn(num_qubits, requires_grad=False)
init_theta  = torch.randn(num_reps, num_qubits, requires_grad=True)
theta       = torch.randn(num_reps, num_layers, num_qubits-1, 2, requires_grad=True)
W           = torch.randn(2**num_qubits, requires_grad=True)

print(qml.draw_mpl(qnn_model)(x, init_theta, theta, W, omega))

# Datasets for Capacity Estimation

In [ ]:
def gen_dataset(N, samples=10, seed=0):
    sizex   = num_qubits
    scale   = 2.
    shift   = -1.

    torch.manual_seed(seed)
    x       = scale*torch.rand(N, sizex, requires_grad=False) + shift
    y       = scale*torch.rand(samples, N, requires_grad=False) + shift

    return x, y

# Training

In [ ]:
# model specs
num_qubits  = 3
num_reps    = 2
num_layers  = 2
omega       = 1.

In [ ]:
import this

In [ ]:
# initial parameters
seed = 0
torch.manual_seed(seed)
init_theta  = torch.randn(num_reps, num_qubits, requires_grad=True)
theta       = torch.randn(num_reps, num_layers, num_qubits-1, 2, requires_grad=True)
W           = torch.randn(2**num_qubits, requires_grad=True)

In [ ]:
# loss function
def square_loss(targets, predictions):
    loss = 0
    for t, p in zip(targets, predictions):
        loss += (t - p) ** 2
    loss = loss / len(targets)
    return 0.5*loss

In [ ]:
# capacity estimation parameters
Nmin     = 1
Nmax     = 5
samples  = 10
steps    = 300
eps_stop = 1e-12

In [ ]:
summary = {}
for N in range(Nmin, Nmax):
    x, y = gen_dataset(N, samples)
    
    mre_sample = []
    for s in range(samples):
        print('===================================')
        def cost(init_theta, theta, W):
            pred = [qnn_model(x[k], init_theta, theta, W) for k in range(N)]
            loss = square_loss(y[s], pred)
            return loss
        
        # optimize
        opt = torch.optim.Adam([init_theta, theta, W], lr=0.1, amsgrad=True)
        for n in range(steps):
            opt.zero_grad()
            loss = cost(init_theta, theta, W)
            loss.backward()
            opt.step()

            if n%10 == 9 or n == steps - 1:
                print(f'{n+1}: {loss}')

            if loss <= eps_stop:
                break

        # compute prediction errors
        y_pred = torch.tensor([qnn_model(x[k], init_theta, theta, W) for k in range(N)], requires_grad=False)
        mre    = torch.mean(torch.abs((y[s]-y_pred)/y_pred))
        mre_sample.append(mre)

    mre_N = torch.mean(torch.tensor(mre_sample))
    summary[f'N = {N}'] = mre_N.item()

In [ ]:
for count, eps in enumerate(summary.values()):
    m = int(np.log2(1./eps.item()))
    C = (count+1)*m
    print(C)
print(torch.numel(init_theta))

In [ ]:
C = [-0.5, 13.1, 2]
max(C)

# Summary

In [ ]:
y_pred = torch.tensor([qnn_model(x[k], init_theta, theta, W) for k in range(N)], requires_grad=False)
mre    = torch.mean(torch.abs((y[s]-y_pred)/y_pred))
print(mre.item())

In [ ]:
# cutoff precision converted to bits of precision
cutoff = np.sqrt(eps_stop)
m      = np.log2(1./cutoff)
print(m)

In [ ]:
print(x)
print(init_theta)
print(theta)
print(W)
print(y[s])
print(y_pred)